version: "3"
services:
    web:
        container_name: web
        build: .
        restart: always
        env_file:
            - .env
        ports:
            - 5000:80
        volumes:
            - .:/holidayplanner
        networks:
            - pgnet
        depends_on:
            - db
    db:
        container_name: db
        image: postgres
        restart: always
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypont-initdb.d/create_tables.sql
        networks:
            - pgnet

networks:
    pgnet:
        driver: bridge

volumes:
    postgres-data:
